image: node:14.20-alpine3.15

services:
  - postgres:12.11-alpine

variables:
  POSTGRES_DB: poca
  POSTGRES_USER: test
  POSTGRES_PASSWORD: "test"
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - build-dockerimage
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test:cov
    - NODE_ENV=ci npm run test:e2e

build-dockerimage:
  stage: build-dockerimage
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug  # see https://docs.gitlab.com/ce/ci/docker/using_kaniko.html
    entrypoint: [""]
  script:
    # With vanilla docker you would be using:
    # docker build --tag poca/poca-2022:latest .
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"`echo -n kevindang01:$CI_REGISTRY_TOKEN | base64`\"}}}" > /kaniko/.docker/config.json
    - mkdir image-digest
    - /kaniko/executor --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY --context "${CI_PROJECT_DIR}" --digest-file image-digest/content --dockerfile "${CI_PROJECT_DIR}"/Dockerfile --destination kevindang01/poca-team-galaxy:latest
    - cat image-digest/content
  only:
    refs:
      - main
      - kevin-docker
      - kevin-terraform
  artifacts:
    paths:
      - image-digest/content
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - cat image-digest/content
    - apk add curl
    - mkdir terraform_install
    - cd terraform_install
    - curl -OJ https://releases.hashicorp.com/terraform/1.3.1/terraform_1.3.1_linux_amd64.zip
    - unzip terraform_1.3.1_linux_amd64.zip && rm terraform_1.3.1_linux_amd64.zip
    - mv terraform /usr/bin/terraform
    - cd ../terraform
    - export TF_IN_AUTOMATION=1
    - export TF_VAR_image_digest="@`cat ../image-digest/content`"
    - terraform init --reconfigure -input=false -backend-config="access_key=${AWS_ACCESS_KEY}" -backend-config="secret_key=${AWS_SECRET_KEY}" -backend-config="region=${AWS_REGION}"
    - terraform apply -input=false -auto-approve --var-file=staging.tfvars --var="db_password=${DB_PASSWORD}"
  only:
    refs:
      - main
      - kevin-terraform
